name: Dist

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout Source (Workflow Run)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Checkout Source (Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'

      - name: Get Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Linux
        run: |
          mkdir -p dist/linux-amd64
          GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o dist/linux-amd64/mstl ./cmd/mstl
          GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o dist/linux-amd64/mstl-gh ./cmd/mstl-gh

      - name: Build Mac
        run: |
          mkdir -p dist/darwin-amd64
          GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o dist/darwin-amd64/mstl ./cmd/mstl
          GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o dist/darwin-amd64/mstl-gh ./cmd/mstl-gh

      - name: Build Windows
        run: |
          mkdir -p dist/windows-amd64
          GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o dist/windows-amd64/mstl.exe ./cmd/mstl
          GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o dist/windows-amd64/mstl-gh.exe ./cmd/mstl-gh

      - name: Upload Artifacts Linux
        uses: actions/upload-artifact@v4
        with:
          name: mstl-binaries-linux-amd64
          path: dist/linux-amd64/
          retention-days: 1

      - name: Upload Artifacts Mac
        uses: actions/upload-artifact@v4
        with:
          name: mstl-binaries-darwin-amd64
          path: dist/darwin-amd64/
          retention-days: 1

      - name: Upload Artifacts Windows
        uses: actions/upload-artifact@v4
        with:
          name: mstl-binaries-windows-amd64
          path: dist/windows-amd64/
          retention-days: 1
