name: Dist

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout Source (Workflow Run)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Checkout Source (Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Get Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o mstl-linux-amd64 ./cmd/mstl

      - name: Build Mac
        run: GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o mstl-darwin-amd64 ./cmd/mstl

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o mstl-windows-amd64.exe ./cmd/mstl

      - name: Build Linux (mstl-gh)
        run: GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o mstl-gh-linux-amd64 ./cmd/mstl-gh

      - name: Build Mac (mstl-gh)
        run: GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o mstl-gh-darwin-amd64 ./cmd/mstl-gh

      - name: Build Windows (mstl-gh)
        run: GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-s -w -X main.commitHash=${{ env.SHORT_SHA }}" -o mstl-gh-windows-amd64.exe ./cmd/mstl-gh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mstl-binaries
          path: |
            mstl-linux-amd64
            mstl-darwin-amd64
            mstl-windows-amd64.exe
            mstl-gh-linux-amd64
            mstl-gh-darwin-amd64
            mstl-gh-windows-amd64.exe
          retention-days: 1
